# Variables
@baseUrl = http://localhost:3333

###

# Get rooms
# @name getRooms
GET {{baseUrl}}/rooms
# GET {{baseUrl}}/rooms?page=1
# GET {{baseUrl}}/rooms?page=1&pageSize=10
# GET {{baseUrl}}/rooms?pageSize=20


###

# Create room
# @name createRoom
POST {{baseUrl}}/rooms
Content-Type: application/json

{
  "name": "Test room 5",
  "description": "This is a test room"
}

###

@roomId = {{createRoom.response.body.$.roomId}}
# @roomId = {{getRooms.response.body.$.[0].id}}

###

# Get room questions
# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions

###

# Create question in a room
# @name createQuestion
POST {{baseUrl}}/rooms/{{roomId}}/questions
Content-Type: application/json

# Good question
{
  "question": "What is React.js?"
}

# Question without answer during local testing
# {
#   "question": "What is Vue.js and its difference from Angular.js?"
# }